# Generated by Django 5.2.4 on 2025-07-25 06:44

import colorfield.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.AddField(
            model_name='todomodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='todos', to='myapp.tag'),
        ),
    ]
