# Generated by Django 5.2.4 on 2025-07-25 11:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tag_todomodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#0099FF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#0099FF', image_field=None, max_length=25, samples=None),
        ),
    ]
