# Generated by Django 5.2.4 on 2025-07-25 11:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_todomodel_color_todomodel_date_todomodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
