# Generated by Django 5.2.4 on 2025-08-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_todomodel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='color',
        ),
    ]
